sudo: required

language: rust

rust: nightly

cache:
  cargo: true

env:
  matrix:
    - ARCH="riscv32"

install:
  - if [ $ARCH = riscv32 ]; then
    export FILE="riscv64-unknown-elf-gcc-20181030-x86_64-linux-ubuntu14";
    wget https://static.dev.sifive.com/dev-tools/$FILE.tar.gz;
    tar xf $FILE.tar.gz;
    export PATH=$PATH:$PWD/$FILE/bin;
    fi

before_script:
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-xbuild || cargo install cargo-xbuild)
  - (test -x $HOME/.cargo/bin/bootimage || cargo install bootimage)
  - (wget https://download.qemu.org/qemu-3.1.0.tar.xz && tar xvJf qemu-3.1.0.tar.xz > /dev/null && cd qemu-3.1.0 && ./configure --target-list=riscv32-softmmu && make)
  - export PATH=$PATH:$PWD/qemu-3.1.0/riscv32-softmmu

script:
  - (cd kernel && make run)
  - python test/test.py